[package]
name = "ti-basic-optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
titokens = { path = "../tokens", features = ["itertools"] }
tifloats = "2.3.0"
itertools = "0.13.0"

[dev-dependencies]
test-files = { path = "../test-files" }